sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: 12345
  redis:
    host: localhost
    port: 6379
    password: tyt
    database: 0
